"""Initial schema V1.0

Revision ID: 1a7cc604bc3f
Revises: 
Create Date: 2026-01-19 20:13:17.555131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7cc604bc3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('created_by_id', sa.String(length=36), nullable=True, comment='ID of user who created this record'),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True, comment='ID of user who last updated this record'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('created_by_id', sa.String(length=36), nullable=True, comment='ID of user who created this record'),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True, comment='ID of user who last updated this record'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_user_active', 'refresh_tokens', ['user_id', 'is_revoked'], unique=False)
    op.create_table('entity_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Sequential version number'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sku_base', sa.String(length=50), nullable=True, comment="Base SKU code for this product version (e.g., 'LPT-PRO')"),
    sa.Column('sku_delimiter', sa.String(length=5), nullable=False, comment="Delimiter for SKU segments (default: '-')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('created_by_id', sa.String(length=36), nullable=True, comment='ID of user who created this record'),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True, comment='ID of user who last updated this record'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_status', 'entity_versions', ['entity_id', 'status'], unique=False)
    op.create_index(op.f('ix_entity_versions_id'), 'entity_versions', ['id'], unique=False)
    op.create_table('configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True, comment='User-defined name'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Lifecycle status: DRAFT (mutable) or FINALIZED (immutable)'),
    sa.Column('is_complete', sa.Boolean(), nullable=False, comment='True if all required fields are filled and validation passes'),
    sa.Column('generated_sku', sa.String(length=100), nullable=True, comment='Cached generated SKU from last calculation'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag for preserving audit trail of FINALIZED records'),
    sa.Column('data', sa.JSON(), nullable=False, comment='Raw input data for re-hydration'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('created_by_id', sa.String(length=36), nullable=True, comment='ID of user who created this record'),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True, comment='ID of user who last updated this record'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_version_id'], ['entity_versions.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_complete', 'configurations', ['is_complete'], unique=False)
    op.create_index('ix_generated_sku', 'configurations', ['generated_sku'], unique=False)
    op.create_index('ix_config_deleted', 'configurations', ['is_deleted'], unique=False)
    op.create_index('ix_config_status', 'configurations', ['status'], unique=False)
    op.create_index(op.f('ix_configurations_is_complete'), 'configurations', ['is_complete'], unique=False)
    op.create_index('ix_user_version', 'configurations', ['user_id', 'entity_version_id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Internal field name'),
    sa.Column('label', sa.String(length=255), nullable=True, comment='Display label for UI'),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_free_value', sa.Boolean(), nullable=False, comment='If True, user can enter any value'),
    sa.Column('default_value', sa.String(length=255), nullable=True, comment='Default value for free-value fields only'),
    sa.Column('sku_modifier_when_filled', sa.String(length=20), nullable=True, comment="SKU segment to append when this free-value field has a non-null value (e.g., 'CUSTOM' for custom engraving)"),
    sa.Column('step', sa.Integer(), nullable=False, comment='Grouping step for UI sections'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Display order within step'),
    sa.ForeignKeyConstraint(['entity_version_id'], ['entity_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False, comment='Internal value'),
    sa.Column('label', sa.String(length=255), nullable=True, comment='Display label for UI'),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sku_modifier', sa.String(length=50), nullable=True, comment="SKU segment for this value (e.g., '16G' for 16GB RAM)"),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_values_id'), 'values', ['id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_version_id', sa.Integer(), nullable=False),
    sa.Column('target_field_id', sa.Integer(), nullable=False),
    sa.Column('target_value_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False, comment='JSON condition criteria'),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_version_id'], ['entity_versions.id'], ),
    sa.ForeignKeyConstraint(['target_field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['target_value_id'], ['values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_values_id'), table_name='values')
    op.drop_table('values')
    op.drop_index(op.f('ix_fields_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index('ix_user_version', table_name='configurations')
    op.drop_index(op.f('ix_configurations_is_complete'), table_name='configurations')
    op.drop_index('ix_config_status', table_name='configurations')
    op.drop_index('ix_config_deleted', table_name='configurations')
    op.drop_index('ix_generated_sku', table_name='configurations')
    op.drop_index('ix_complete', table_name='configurations')
    op.drop_table('configurations')
    op.drop_index(op.f('ix_entity_versions_id'), table_name='entity_versions')
    op.drop_index('ix_entity_status', table_name='entity_versions')
    op.drop_table('entity_versions')
    op.drop_index('ix_user_active', table_name='refresh_tokens')
    op.drop_index('ix_token_hash', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
