"""add bom tables and configuration bom total price

Revision ID: ede7b2b33ade
Revises: 1a7cc604bc3f
Create Date: 2026-04-03 18:45:11.925877

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ede7b2b33ade"
down_revision: str | Sequence[str] | None = "1a7cc604bc3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bom_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_version_id", sa.Integer(), nullable=False),
        sa.Column("parent_bom_item_id", sa.Integer(), nullable=True),
        sa.Column("bom_type", sa.String(length=20), nullable=False),
        sa.Column("part_number", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.String(length=100),
            nullable=True,
            comment="Grouping label (e.g., 'Chassis', 'Electronics')",
        ),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), server_default="1", nullable=False),
        sa.Column("quantity_from_field_id", sa.Integer(), nullable=True),
        sa.Column(
            "unit_of_measure",
            sa.String(length=20),
            nullable=True,
            comment="e.g., 'pcs', 'm', 'kg'",
        ),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=12, scale=4),
            nullable=True,
            comment="Required for COMMERCIAL/BOTH, rejected for TECHNICAL",
        ),
        sa.Column(
            "sequence",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Ordering among siblings",
        ),
        sa.ForeignKeyConstraint(
            ["entity_version_id"],
            ["entity_versions.id"],
        ),
        sa.ForeignKeyConstraint(["parent_bom_item_id"], ["bom_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["quantity_from_field_id"], ["fields.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bom_items_id"), "bom_items", ["id"], unique=False)
    op.create_index("ix_bom_parent", "bom_items", ["parent_bom_item_id"], unique=False)
    op.create_index("ix_bom_version", "bom_items", ["entity_version_id"], unique=False)
    op.create_table(
        "bom_item_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bom_item_id", sa.Integer(), nullable=False),
        sa.Column("entity_version_id", sa.Integer(), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=False, comment="JSON condition criteria"),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["bom_item_id"], ["bom_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["entity_version_id"],
            ["entity_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bom_item_rules_id"), "bom_item_rules", ["id"], unique=False)
    op.create_index("ix_bomrule_item", "bom_item_rules", ["bom_item_id"], unique=False)
    op.create_index("ix_bomrule_version", "bom_item_rules", ["entity_version_id"], unique=False)
    op.add_column(
        "configurations",
        sa.Column(
            "bom_total_price",
            sa.Numeric(precision=12, scale=4),
            nullable=True,
            comment="Cached BOM commercial total from last calculation",
        ),
    )
    op.drop_index(op.f("ix_generated_sku"), table_name="configurations")
    op.create_index(op.f("ix_configurations_bom_total_price"), "configurations", ["bom_total_price"], unique=False)
    op.create_index(op.f("ix_configurations_generated_sku"), "configurations", ["generated_sku"], unique=False)
    op.alter_column(
        "rules",
        "target_value_id",
        existing_type=sa.INTEGER(),
        comment="Only used for AVAILABILITY rules: specifies which Value this rule controls",
        existing_nullable=True,
    )
    op.alter_column(
        "rules",
        "error_message",
        existing_type=sa.VARCHAR(),
        comment="Only used for VALIDATION rules: message shown when validation fails",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rules",
        "error_message",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Only used for VALIDATION rules: message shown when validation fails",
        existing_nullable=True,
    )
    op.alter_column(
        "rules",
        "target_value_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Only used for AVAILABILITY rules: specifies which Value this rule controls",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_configurations_generated_sku"), table_name="configurations")
    op.drop_index(op.f("ix_configurations_bom_total_price"), table_name="configurations")
    op.create_index(op.f("ix_generated_sku"), "configurations", ["generated_sku"], unique=False)
    op.drop_column("configurations", "bom_total_price")
    op.drop_index("ix_bomrule_version", table_name="bom_item_rules")
    op.drop_index("ix_bomrule_item", table_name="bom_item_rules")
    op.drop_index(op.f("ix_bom_item_rules_id"), table_name="bom_item_rules")
    op.drop_table("bom_item_rules")
    op.drop_index("ix_bom_version", table_name="bom_items")
    op.drop_index("ix_bom_parent", table_name="bom_items")
    op.drop_index(op.f("ix_bom_items_id"), table_name="bom_items")
    op.drop_table("bom_items")
    # ### end Alembic commands ###
